spring.application.name=demo

spring.datasource.url=jdbc:postgresql://db.pjkkywbktfhswibvgksp.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=5pl6ZjdEFkc5UW

spring.jpa.hibernate.ddl-auto=validate