spring.application.name=demo

# Gestione della porta dinamica di Render
server.port=${PORT:8080}

# Parametri Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-0-eu-west-2.pooler.supabase.com:5432/postgres?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres.pjkkywbktfhswibvgksp}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:5pl6ZjdEFkc5UW}

# Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect